name: ssh
on:
  watch:
    types: started

    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@v1
 
    
       
    - name: ssh
      run: |
        gh
      



    - name: cfg
      run: |
        sudo apt update
        sudo sleep 999
