name: ssh
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@v1
 
    
       
    - name: ssh
      run: |
        sudo apt update
        echo -e "${{ secrets.PASSWD }}\n${{ secrets.PASSWD }}" | sudo passwd runner
        curl -s https://install.zerotier.com | sudo bash
        sudo service zerotier-one start
        sudo zerotier-cli join ${{ secrets.ID }}
        
      



    - name: cfg
      run: |
        sudo apt update
        sudo sleep 9h
