name: ssh
on:
  watch:
    types: started

    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@v1
 
    
       
    - name: ssh
      run: |
        cd ~
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        mkdir .cloudflared
        cd .cloudflared
        
        wget https://gitee.com/googlerhyme/ff/raw/master/1.zip
        unzip -P "${{ secrets.PASSWD }}" 1.zip
        pwd
        ls
        echo 'pspsps'
        sudo ps -A
        sudo  cloudflared tunnel --name ssh --url tcp://127.0.0.1:22



    - name: cfg
      if: ${{ failure() }}
      run: sleep 9d
